package io.github.aedev.flow.ui.screens.player.state

import io.github.aedev.flow.player.EnhancedPlayerManager
import io.github.aedev.flow.player.state.SubtitleOption
import io.github.aedev.flow.player.stream.CaptionTrackResolver
import io.github.aedev.flow.player.subtitle.SubtitleChoice

internal object SubtitleSelection {
    fun applyAt(
        subtitles: List<SubtitleOption>,
        index: Int,
        rememberLanguage: (String) -> Unit,
    ): Boolean {
        val subtitle = subtitles.getOrNull(index) ?: return false
        EnhancedPlayerManager.getInstance().selectSubtitle(subtitle.url)
        subtitle.language.takeIf { it.isNotBlank() }?.let(rememberLanguage)
        return true
    }

    /** Turns captions on in [languageTag], or the best track there is; false when the video has none. */
    fun enable(
        subtitles: List<SubtitleOption>,
        languageTag: String?,
        rememberLanguage: (String) -> Unit,
    ): Boolean {
        val choice = SubtitleChoice.preferred(subtitles, languageTag) ?: return false
        return applyAt(subtitles, subtitles.indexOf(choice), rememberLanguage)
    }

    /**
     * The track to drop to when [failedIndex] gave up, or null when nothing is worth trying.
     *
     * Only a translation falls back: it is a machine pass over a track that is usually still
     * loadable, so the same language authored or auto-generated is the closest thing to what the
     * user asked for, and any untranslated track beats switching subtitles off.
     */
    fun fallbackIndexFor(
        subtitles: List<SubtitleOption>,
        failedIndex: Int,
        failedLanguage: String?,
        wasTranslated: Boolean,
    ): Int? {
        if (!wasTranslated) return null
        val candidates =
            subtitles.withIndex().filter { (index, option) ->
                index != failedIndex && !option.isTranslated
            }
        if (candidates.isEmpty()) return null
        val sameLanguage =
            failedLanguage?.let { wanted ->
                CaptionTrackResolver.bestMatch(
                    candidates = candidates,
                    languageTag = wanted,
                    tagOf = { it.value.language },
                    isAutoGenerated = { it.value.isAutoGenerated },
                )
            }
        return (sameLanguage ?: candidates.firstOrNull { !it.value.isAutoGenerated } ?: candidates.first()).index
    }

    /**
     * The subtitle to move to after the audio track changes to [audioLanguage], or null to stay put.
     *
     * Derived from the language codes rather than from the response's own `captions.audioTracks`
     * pairing: that array maps every dub to the identical caption set and the identical default
     * (the original language), on every dubbed video probed, so it carries nothing to act on.
     *
     * Only moves an already-visible subtitle. Switching audio should not turn captions on for
     * someone who had them off.
     */
    fun subtitleFollowingAudio(
        subtitles: List<SubtitleOption>,
        audioLanguage: String?,
        selectedUrl: String?,
    ): Int? {
        if (selectedUrl.isNullOrBlank()) return null
        val wanted = audioLanguage?.takeIf { it.isNotBlank() } ?: return null
        val match =
            CaptionTrackResolver.bestMatch(
                candidates = subtitles,
                languageTag = wanted,
                tagOf = { it.language },
                isAutoGenerated = { it.isAutoGenerated || it.isTranslated },
            ) ?: return null
        if (match.url == selectedUrl) return null
        return subtitles.indexOf(match).takeIf { it >= 0 }
    }

    fun disable() {
        EnhancedPlayerManager.getInstance().selectSubtitle(null)
    }
}
