package io.github.aedev.flow.data.video.downloader.request

import io.github.aedev.flow.data.video.downloader.tags.DownloadKind
import io.github.aedev.flow.data.video.downloader.tags.DownloadTags
import kotlinx.serialization.Serializable
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.json.Json

/**
 * What the user asked to download, stored with the download row. Streams are resolved from this
 * only when a download slot is free, so a request that waits in the queue for hours never runs on
 * a URL that expired while it waited.
 */
@Serializable
data class DownloadRequest(
    val tags: DownloadTags,
    val audioOnly: Boolean = false,
    /** Tallest height wanted; null follows the default download quality, 0 means the best there is. */
    val targetHeight: Int? = null,
    val videoCodec: String? = null,
    /** The exact streams a dialog picked, kept when the fresh extraction still offers them. */
    val videoItag: Int? = null,
    val audioItag: Int? = null,
    val audioTrackId: String? = null,
    val audioLanguage: String? = null,
    val collectionId: String? = null,
    val threads: Int? = null,
    val durationSeconds: Int = 0,
    /** Credited artists with their channel ids, for a song's artist links; the tags carry the names. */
    val artists: List<StoredArtist> = emptyList(),
    /** The caption track saved as a file beside a video; null leaves it to the Downloads setting. */
    val subtitle: DownloadSubtitle? = null,
    /** Where that file was written, so deleting the download removes it too. */
    val subtitleFile: String? = null,
) {
    val videoId: String get() = tags.videoId
    val kind: DownloadKind get() = tags.kind
    val isMusic: Boolean get() = tags.kind == DownloadKind.MUSIC

    /** Music is always audio; so is anything asked for as audio only. */
    val wantsAudioOnly: Boolean get() = audioOnly || isMusic

    fun encode(): String = json.encodeToString(serializer(), this)

    companion object {
        private val json =
            Json {
                ignoreUnknownKeys = true
                encodeDefaults = false
            }

        fun decode(raw: String?): DownloadRequest? = raw?.let { runCatching { json.decodeFromString(serializer(), it) }.getOrNull() }
    }
}

/**
 * The caption track a download saves beside the video, by language and kind. A blank language is
 * an explicit "no file"; [ANY_LANGUAGE] takes the first authored track there is.
 */
@Serializable
data class DownloadSubtitle(
    val languageTag: String,
    val autoGenerated: Boolean = false,
    val translated: Boolean = false,
) {
    val isOff: Boolean get() = languageTag.isBlank()

    companion object {
        const val ANY_LANGUAGE = "*"
        val OFF = DownloadSubtitle(languageTag = "")
    }
}

/** A credited artist as a download keeps it: the name shown and the channel it opens. */
@Serializable
data class StoredArtist(
    val name: String,
    val id: String? = null,
) {
    companion object {
        private val json = Json { ignoreUnknownKeys = true }
        private val listSerializer = ListSerializer(serializer())

        fun encode(artists: List<StoredArtist>): String = json.encodeToString(listSerializer, artists)

        fun decode(raw: String?): List<StoredArtist> =
            raw?.let { runCatching { json.decodeFromString(listSerializer, it) }.getOrNull() }.orEmpty()
    }
}
