package io.github.aedev.flow.data.localmedia

import android.content.Context
import android.content.Intent
import android.net.Uri
import android.provider.DocumentsContract
import android.provider.OpenableColumns
import android.util.Log
import dagger.hilt.android.qualifiers.ApplicationContext
import io.github.aedev.flow.player.stream.CaptionFormat
import io.github.aedev.flow.player.stream.CaptionSource
import io.github.aedev.flow.player.stream.ResolvedCaption
import io.github.aedev.flow.utils.PerformanceDispatcher
import kotlinx.coroutines.withContext
import java.io.File
import java.util.Locale
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Subtitle files for videos on the device: the ones beside a video, and the ones someone picked
 * for it. MediaStore indexes subtitle files like `.lrc` lyrics, so the video permission that lists
 * a video lets Flow read the files next to it. Nothing here touches the network.
 */
@Singleton
class LocalSubtitles
    @Inject
    constructor(
        @param:ApplicationContext private val context: Context,
        private val store: LocalSubtitleStore,
    ) {
        /**
         * The subtitle files that belong to the video at [videoPath], a content Uri or a file path:
         * beside it, in a `Subs` folder next to it, or in `Subs/<video name>/`.
         */
        suspend fun beside(videoPath: String): List<ResolvedCaption> =
            withContext(PerformanceDispatcher.diskIO) {
                val video = fileOf(videoPath) ?: return@withContext emptyList()
                val folder = video.parentFile ?: return@withContext emptyList()
                val entries = folder.listFilesSafely()
                val videosInFolder = entries.count { it.isFile && it.extension.lowercase() in VideoExtensions }
                val candidates =
                    entries.filter { it.isFile }.map { SubtitleFileCandidate(it.name) } +
                        entries
                            .filter { it.isDirectory && it.name.lowercase() in SubtitleFolderNames }
                            .flatMap { subs -> subtitleFolderCandidates(subs, video.nameWithoutExtension) }
                matchingSubtitleFiles(video.name, candidates, videosInFolder).mapNotNull { match ->
                    readableUrl(Uri.fromFile(File(folder, match.path)), match.format)?.let { url ->
                        ResolvedCaption(
                            match.languageTag,
                            isAutoGenerated = false,
                            url = url,
                            format = match.format,
                            label = match.path,
                            source = CaptionSource.SIDECAR,
                        )
                    }
                }
            }

        private fun subtitleFolderCandidates(
            subs: File,
            videoStem: String,
        ): List<SubtitleFileCandidate> {
            val entries = subs.listFilesSafely()
            val ownFolder = entries.firstOrNull { it.isDirectory && it.name.equals(videoStem, ignoreCase = true) }
            return entries.filter { it.isFile }.map { SubtitleFileCandidate("${subs.name}/${it.name}") } +
                ownFolder
                    ?.listFilesSafely()
                    ?.filter { it.isFile }
                    ?.map { SubtitleFileCandidate("${subs.name}/${ownFolder.name}/${it.name}", inVideoSubfolder = true) }
                    .orEmpty()
        }

        private fun File.listFilesSafely(): List<File> = runCatching { listFiles()?.toList() }.getOrNull().orEmpty()

        /** The folder of the video at [videoPath] as a document the system file picker can open in. */
        suspend fun folderDocument(videoPath: String): Uri? =
            withContext(PerformanceDispatcher.diskIO) {
                val folder = fileOf(videoPath)?.parentFile ?: return@withContext null
                externalStorageDocumentId(folder.absolutePath)?.let { DocumentsContract.buildDocumentUri(EXTERNAL_STORAGE_AUTHORITY, it) }
            }

        /** The subtitle files picked for [videoId] that can still be read. */
        suspend fun picked(videoId: String): List<ResolvedCaption> =
            withContext(PerformanceDispatcher.diskIO) {
                store.forVideo(videoId).picks.mapNotNull { pick -> pickedCaption(Uri.parse(pick.uri), pick.name) }
            }

        /** The caption timing set for [videoId], in milliseconds. */
        suspend fun offsetMs(videoId: String): Long = store.forVideo(videoId).offsetMs

        suspend fun setOffsetMs(
            videoId: String,
            offsetMs: Long,
        ) = store.setOffset(videoId, offsetMs)

        /** Remembers [uri] for [videoId]; null when it is not a subtitle file Flow can read. */
        suspend fun pick(
            videoId: String,
            uri: Uri,
        ): ResolvedCaption? =
            withContext(PerformanceDispatcher.diskIO) {
                val name = displayName(uri) ?: return@withContext null
                val caption = pickedCaption(uri, name) ?: return@withContext null
                runCatching { context.contentResolver.takePersistableUriPermission(uri, Intent.FLAG_GRANT_READ_URI_PERMISSION) }
                    .onFailure { Log.w(TAG, "No lasting read access to $name", it) }
                store.addPick(videoId, PickedSubtitle(uri.toString(), name))
                caption
            }

        private fun pickedCaption(
            uri: Uri,
            name: String,
        ): ResolvedCaption? {
            val format = CaptionFormat.ofExtension(name.substringAfterLast('.', "")) ?: return null
            val url = readableUrl(uri, format) ?: return null
            val language = subtitleLanguageOf(name.substringBeforeLast('.').split('.').drop(1))
            return ResolvedCaption(
                language,
                isAutoGenerated = false,
                url = url,
                format = format,
                label = name,
                source = CaptionSource.PICKED,
            )
        }

        /**
         * A URL the player can read [uri] from. Media3 reads subtitles as UTF-8 unless they start
         * with a byte-order mark, so a file in an older code page is decoded and copied to the cache.
         */
        private fun readableUrl(
            uri: Uri,
            format: CaptionFormat,
        ): String? =
            try {
                val bytes =
                    context.contentResolver.openInputStream(uri)?.use { input ->
                        input.readAtMost(MAX_SUBTITLE_BYTES)
                    } ?: return null
                when {
                    bytes.size > MAX_SUBTITLE_BYTES -> {
                        null
                    }

                    isUnicodeText(bytes) -> {
                        uri.toString()
                    }

                    else -> {
                        val text = decodeTextFile(bytes) { legacyTextCharset(Locale.getDefault()) }
                        val copy =
                            File(
                                File(context.cacheDir, CACHE_DIR).apply { mkdirs() },
                                "${uri.toString().hashCode().toUInt()}.${format.name.lowercase(Locale.ROOT)}",
                            )
                        copy.writeText(text)
                        Uri.fromFile(copy).toString()
                    }
                }
            } catch (e: Exception) {
                Log.w(TAG, "Could not read the subtitle file $uri: ${e.message}")
                null
            }

        private fun fileOf(videoPath: String): File? {
            val uri = Uri.parse(videoPath)
            val path =
                when (uri.scheme) {
                    "content" -> context.mediaStoreDataPath(uri)
                    "file" -> uri.path
                    else -> videoPath.takeIf { it.startsWith("/") }
                }
            return path?.let(::File)
        }

        private fun displayName(uri: Uri): String? =
            runCatching {
                context.contentResolver.query(uri, arrayOf(OpenableColumns.DISPLAY_NAME), null, null, null)?.use { cursor ->
                    if (cursor.moveToFirst()) cursor.getString(0) else null
                }
            }.getOrNull() ?: uri.lastPathSegment?.substringAfterLast('/')

        private companion object {
            const val TAG = "LocalSubtitles"
            const val CACHE_DIR = "subtitles"
            const val MAX_SUBTITLE_BYTES = 8 * 1024 * 1024
            const val EXTERNAL_STORAGE_AUTHORITY = "com.android.externalstorage.documents"
        }
    }
