package io.github.aedev.flow.ui.components.videoplayer.subtitle

import android.graphics.Typeface
import android.util.TypedValue
import androidx.compose.foundation.layout.BoxWithConstraints
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.offset
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.toArgb
import androidx.compose.ui.unit.dp
import androidx.compose.ui.viewinterop.AndroidView
import androidx.media3.common.Player
import androidx.media3.common.text.Cue
import androidx.media3.common.text.CueGroup
import androidx.media3.ui.CaptionStyleCompat
import androidx.media3.ui.SubtitleView
import io.github.aedev.flow.player.EnhancedPlayerManager
import io.github.aedev.flow.player.subtitle.toRollingCaptionText

/**
 * Draws the player's captions with Media3's [SubtitleView], laid out over the picture rather than
 * the whole player, so letterbox bars never separate the two.
 *
 * @param bottomPadding the gap, in dp, between the bottom of the picture and the lowest line.
 * @param resizeMode the player's mode: 0 fit, 1 fill, 2 zoom.
 */
@Composable
fun Media3SubtitleOverlay(
    enabled: Boolean,
    isAutoGenerated: Boolean,
    modifier: Modifier = Modifier,
    style: SubtitleStyle = SubtitleStyle(),
    bottomPadding: Float = style.bottomPadding,
    videoAspectRatio: Float? = null,
    resizeMode: Int = 0,
) {
    var cues by remember { mutableStateOf(emptyList<Cue>()) }
    val player = EnhancedPlayerManager.getInstance().getPlayer()

    DisposableEffect(player) {
        if (player == null) {
            onDispose { }
        } else {
            val listener =
                object : Player.Listener {
                    override fun onCues(cueGroup: CueGroup) {
                        cues = cueGroup.cues
                    }
                }
            player.addListener(listener)
            cues = player.currentCues.cues
            onDispose {
                player.removeListener(listener)
            }
        }
    }

    if (!enabled) return

    val shownCues = remember(cues, isAutoGenerated) { cues.shown(isAutoGenerated) }

    // Not wrapped in AnimatedVisibility: cues empty out in the gap between every caption, which
    // would tear the SubtitleView down and re-inflate it hundreds of times per video. An empty
    // cue list already draws nothing.
    BoxWithConstraints(modifier = modifier.fillMaxSize()) {
        val area = subtitleArea(maxWidth.value, maxHeight.value, videoAspectRatio, resizeMode)
        // An inset, not SubtitleView's bottom padding fraction: Media3 applies that fraction only
        // to cues without a line of their own, and WebVTT gives every cue one counted up from the
        // bottom, so downloaded and device captions would sit on the edge.
        // Kept short of the picture's top by room for two lines, so the text never leaves it.
        val inset = bottomPadding.coerceIn(0f, (area.height - style.fontSize * LINES_KEPT_IN_VIEW).coerceAtLeast(0f))
        StyledSubtitles(
            cues = shownCues,
            style = style,
            modifier =
                Modifier
                    .offset(area.left.dp, area.top.dp)
                    .size(area.width.dp, area.height.dp)
                    .padding(start = SideInset, end = SideInset, bottom = inset.dp),
        )
    }
}

/** Media3's [SubtitleView] drawing [cues] in [style], lines stacked up from its bottom edge. */
@Composable
internal fun StyledSubtitles(
    cues: List<Cue>,
    style: SubtitleStyle,
    modifier: Modifier = Modifier,
) {
    val captionStyle = remember(style) { style.toCaptionStyle() }
    AndroidView(
        modifier = modifier,
        factory = { context ->
            SubtitleView(context).apply {
                setApplyEmbeddedStyles(true)
                setApplyEmbeddedFontSizes(false)
                setBottomPaddingFraction(0f)
            }
        },
        update = { view ->
            view.setFixedTextSize(TypedValue.COMPLEX_UNIT_SP, style.fontSize)
            view.setStyle(captionStyle)
            view.setCues(cues)
        },
    )
}

private fun SubtitleStyle.toCaptionStyle(): CaptionStyleCompat =
    CaptionStyleCompat(
        textColor.toArgb(),
        backgroundColor.toArgb(),
        windowColor.toArgb(),
        when (edgeType) {
            SubtitleEdgeType.NONE -> CaptionStyleCompat.EDGE_TYPE_NONE
            SubtitleEdgeType.OUTLINE -> CaptionStyleCompat.EDGE_TYPE_OUTLINE
            SubtitleEdgeType.DROP_SHADOW -> CaptionStyleCompat.EDGE_TYPE_DROP_SHADOW
            SubtitleEdgeType.RAISED -> CaptionStyleCompat.EDGE_TYPE_RAISED
            SubtitleEdgeType.DEPRESSED -> CaptionStyleCompat.EDGE_TYPE_DEPRESSED
        },
        edgeColor.toArgb(),
        if (isBold) Typeface.DEFAULT_BOLD else Typeface.DEFAULT,
    )

/**
 * Authored tracks keep their own lines, styling and placement, and image subtitles from device
 * files keep their bitmaps. Speech-recognised tracks are rebuilt into the one latest line.
 */
private fun List<Cue>.shown(isAutoGenerated: Boolean): List<Cue> =
    if (isAutoGenerated) {
        toRollingCaptionText()?.let { listOf(Cue.Builder().setText(it).build()) }.orEmpty()
    } else {
        filter { !it.text.isNullOrBlank() || it.bitmap != null }
    }

private val SideInset = 16.dp
private const val LINES_KEPT_IN_VIEW = 2.5f
