package io.github.aedev.flow.player.stream

import android.util.Log
import io.github.aedev.flow.innertube.models.response.PlayerResponse
import java.util.Locale

object CaptionTrackResolver {
    private const val TAG = "CaptionTrackResolver"

    /** Marks a track produced by YouTube's machine translation of another caption track. */
    const val TRANSLATED_PARAM = "tlang"

    const val NO_PREFERRED_LANGUAGE = "none"

    /**
     * @param format timedtext format requested for authored tracks. Defaults to
     *   [CaptionFormat.SRV3], YouTube's own styled/positioned caption XML, decoded by
     *   [io.github.aedev.flow.player.renderer.subtitle.Srv3SubtitleParser]. Callers that need the
     *   plain-text `vtt` conversion (offline downloads validate and store the raw response body)
     *   pass [CaptionFormat.VTT] explicitly. Auto-generated (ASR) tracks always stay on `vtt`
     *   regardless: their srv3 form is a roll-up stream of word-timed segments, which the rolling
     *   caption renderer does not reconstruct.
     * @param translateTo a BCP-47 tag to machine-translate into when the video carries no track in
     *   that language. Only one is produced: the response offers up to 156 translation languages,
     *   and materialising them all would bury the authored tracks in the picker.
     */
    fun resolve(
        playerResponse: PlayerResponse,
        format: CaptionFormat = CaptionFormat.SRV3,
        translateTo: String? = null,
    ): List<ResolvedCaption> = resolveTracklist(playerResponse.captions?.playerCaptionsTracklistRenderer, format, translateTo)

    fun resolveTracklist(
        renderer: PlayerResponse.Captions.PlayerCaptionsTracklistRenderer?,
        format: CaptionFormat = CaptionFormat.SRV3,
        translateTo: String? = null,
    ): List<ResolvedCaption> {
        if (renderer == null) return emptyList()
        val tracks =
            renderer.captionTracks
                ?.filter { !it.baseUrl.isNullOrBlank() && !it.languageCode.isNullOrBlank() }
                .orEmpty()
        if (tracks.isEmpty()) return emptyList()

        val result =
            tracks.map { track ->
                val autoGenerated = track.kind == "asr"
                val trackFormat = if (autoGenerated) CaptionFormat.VTT else format
                ResolvedCaption(
                    languageTag = track.languageCode!!,
                    isAutoGenerated = autoGenerated,
                    url = timedTextUrl(track.baseUrl!!, trackFormat),
                    format = trackFormat,
                )
            }

        val translated = translatedTrack(renderer, tracks, result, translateTo, format)
        Log.d(TAG, "Resolved ${result.size} caption tracks from InnerTube captions (translated=${translated != null})")
        return if (translated == null) result else result + translated
    }

    private fun translatedTrack(
        renderer: PlayerResponse.Captions.PlayerCaptionsTracklistRenderer,
        tracks: List<PlayerResponse.Captions.CaptionTrack>,
        resolved: List<ResolvedCaption>,
        translateTo: String?,
        format: CaptionFormat,
    ): ResolvedCaption? {
        val wanted = translateTo?.takeIf { it.isNotBlank() && it != NO_PREFERRED_LANGUAGE } ?: return null
        val offered =
            renderer.translationLanguages
                ?.mapNotNull { it.languageCode }
                ?.firstOrNull { baseLanguage(it) == baseLanguage(wanted) }
                ?: return null
        val alreadyCovered =
            bestMatch(
                candidates = resolved,
                languageTag = offered,
                tagOf = { it.languageTag },
                isAutoGenerated = { it.isAutoGenerated },
            ) != null
        if (alreadyCovered) return null

        // Authored source first: a translation of a transcript reads better than a translation of
        // speech recognition, and an ASR source also forces the plain-text vtt form.
        val source =
            tracks.firstOrNull { it.isTranslatable == true && it.kind != "asr" }
                ?: tracks.firstOrNull { it.isTranslatable == true }
                ?: return null
        val sourceFormat = if (source.kind == "asr") CaptionFormat.VTT else format
        return ResolvedCaption(
            languageTag = offered,
            isAutoGenerated = true,
            url = "${timedTextUrl(source.baseUrl!!, sourceFormat)}&$TRANSLATED_PARAM=$offered",
            format = sourceFormat,
        )
    }

    private fun timedTextUrl(
        baseUrl: String,
        format: CaptionFormat,
    ): String {
        val separatorIndex = baseUrl.indexOf('?')
        val path = if (separatorIndex >= 0) baseUrl.substring(0, separatorIndex) else baseUrl
        val query = if (separatorIndex >= 0) baseUrl.substring(separatorIndex + 1) else ""

        val retained =
            query
                .split('&')
                .filter { it.isNotEmpty() && !it.isParam("fmt") && !it.isParam(TRANSLATED_PARAM) }
                .toMutableList()

        retained.add("fmt=${format.fmtQueryValue ?: CaptionFormat.SRV3.fmtQueryValue}")

        return "$path?${retained.joinToString("&")}"
    }

    private fun String.isParam(name: String): Boolean = startsWith("$name=", ignoreCase = true) || equals(name, ignoreCase = true)

    fun <T> bestMatch(
        candidates: List<T>,
        languageTag: String?,
        tagOf: (T) -> String?,
        isAutoGenerated: (T) -> Boolean,
    ): T? {
        val wanted = languageTag?.takeIf { it.isNotBlank() && it != NO_PREFERRED_LANGUAGE } ?: return null
        val wantedBase = baseLanguage(wanted)
        val ranked =
            candidates
                .filter { baseLanguage(tagOf(it).orEmpty()) == wantedBase }
                .sortedWith(
                    compareBy<T> { !tagOf(it).equals(wanted, ignoreCase = true) }
                        .thenBy { isAutoGenerated(it) },
                )
        return ranked.firstOrNull()
    }

    private fun baseLanguage(tag: String): String =
        tag
            .substringBefore('-')
            .substringBefore('_')
            .lowercase(Locale.ROOT)
}
