package io.github.aedev.flow.player.stream

import androidx.media3.common.MimeTypes
import io.github.aedev.flow.player.renderer.subtitle.Srv3SubtitleParser

/**
 * The text format of a caption track. [fmtQueryValue] is YouTube's timedtext `fmt` spelling, set
 * only for the formats that endpoint serves.
 */
enum class CaptionFormat(
    val mimeType: String,
    val fmtQueryValue: String? = null,
) {
    SRV3(Srv3SubtitleParser.MIME_TYPE, "srv3"),
    VTT(MimeTypes.TEXT_VTT, "vtt"),
    SRT(MimeTypes.APPLICATION_SUBRIP),
    SSA(MimeTypes.TEXT_SSA),
    TTML(MimeTypes.APPLICATION_TTML),
    ;

    companion object {
        /** The format a subtitle file's extension names, or null for one Media3 cannot read. */
        fun ofExtension(extension: String): CaptionFormat? =
            when (extension.lowercase()) {
                "srt" -> SRT
                "vtt" -> VTT
                "ass", "ssa" -> SSA
                "ttml", "dfxp" -> TTML
                else -> null
            }
    }
}

/** Where a caption track came from, which decides how it is labelled and whether it is kept. */
enum class CaptionSource {
    YOUTUBE,
    STORED,
    SIDECAR,
    PICKED,
}

/**
 * One caption track ready to fetch: a signed timedtext URL, a `file:` URI for a track stored beside
 * a download, or a `content:` URI for a subtitle file on the device.
 *
 * @param label the name a file gave the track, shown in place of the language name.
 */
data class ResolvedCaption(
    val languageTag: String,
    val isAutoGenerated: Boolean,
    val url: String,
    val format: CaptionFormat,
    val label: String? = null,
    val source: CaptionSource = CaptionSource.YOUTUBE,
) {
    val isTranslated: Boolean
        get() = url.contains("&${CaptionTrackResolver.TRANSLATED_PARAM}=")
}
