package io.github.aedev.flow.data.video.downloader.subtitle

import com.google.common.truth.Truth.assertThat
import io.github.aedev.flow.data.video.downloader.request.DownloadRequest
import io.github.aedev.flow.data.video.downloader.request.DownloadSubtitle
import io.github.aedev.flow.data.video.downloader.tags.DownloadKind
import io.github.aedev.flow.data.video.downloader.tags.DownloadTags
import io.github.aedev.flow.player.stream.CaptionFormat
import io.github.aedev.flow.player.stream.ResolvedCaption
import org.junit.Test

class DownloadSubtitlePickTest {
    private fun caption(
        language: String,
        auto: Boolean = false,
        translated: Boolean = false,
    ) = ResolvedCaption(
        languageTag = language,
        isAutoGenerated = auto,
        url = "https://yt/timedtext?lang=$language" + if (translated) "&tlang=$language" else "",
        format = CaptionFormat.VTT,
    )

    private val tracks = listOf(caption("en", auto = true), caption("en"), caption("de-DE"), caption("fr", translated = true))

    @Test
    fun `the chosen language and kind win, then the closest language`() {
        assertThat(pickDownloadCaption(tracks, DownloadSubtitle("en", autoGenerated = true))).isEqualTo(tracks[0])
        assertThat(pickDownloadCaption(tracks, DownloadSubtitle("en"))).isEqualTo(tracks[1])
        assertThat(pickDownloadCaption(tracks, DownloadSubtitle("de"))).isEqualTo(tracks[2])
        assertThat(pickDownloadCaption(tracks, DownloadSubtitle("fr"))).isNull()
        assertThat(pickDownloadCaption(tracks, DownloadSubtitle("fr", translated = true))).isEqualTo(tracks[3])
    }

    @Test
    fun `any language takes the first authored track and off takes none`() {
        assertThat(pickDownloadCaption(tracks, DownloadSubtitle(DownloadSubtitle.ANY_LANGUAGE))).isEqualTo(tracks[1])
        assertThat(pickDownloadCaption(tracks, DownloadSubtitle.OFF)).isNull()
    }

    @Test
    fun `the choice and the written file survive the stored request`() {
        val request =
            DownloadRequest(
                DownloadTags(kind = DownloadKind.VIDEO, videoId = "v", title = "Video"),
                subtitle = DownloadSubtitle("en", autoGenerated = true),
                subtitleFile = "/storage/emulated/0/Download/Flow/Video.en.srt",
            )

        assertThat(DownloadRequest.decode(request.encode())).isEqualTo(request)
        assertThat(DownloadRequest.decode(request.copy(subtitle = null, subtitleFile = null).encode())?.subtitle).isNull()
    }
}
