package io.github.aedev.flow.data.video.downloader.subtitle

import androidx.media3.common.text.Cue
import androidx.media3.extractor.text.CuesWithTiming
import com.google.common.truth.Truth.assertThat
import org.junit.Test

class SrtTextTest {
    private fun segment(
        startMs: Long,
        endMs: Long,
        vararg texts: String,
    ) = CuesWithTiming(texts.map { Cue.Builder().setText(it).build() }, startMs * 1_000, (endMs - startMs) * 1_000)

    @Test
    fun `authored segments keep their text and times`() {
        val srt =
            srtText(listOf(segment(1_000, 3_500, "First line", "second cue"), segment(65_250, 67_000, "Later")), isAutoGenerated = false)

        assertThat(srt).isEqualTo("1\n00:00:01,000 --> 00:00:03,500\nFirst line\nsecond cue\n\n2\n00:01:05,250 --> 00:01:07,000\nLater\n")
    }

    @Test
    fun `speech recognised segments show each line once for as long as it is spoken`() {
        val srt =
            srtText(
                listOf(
                    segment(320, 2_790, " \n[Music]"),
                    segment(2_790, 2_800, " \n "),
                    segment(2_800, 5_790, " \nWe're no strangers to"),
                    segment(5_790, 5_800, "We're no strangers to\n "),
                    segment(5_800, 9_950, "We're no strangers to\nlove. You know the rules"),
                ),
                isAutoGenerated = true,
            )

        assertThat(srt).isEqualTo(
            "1\n00:00:00,320 --> 00:00:02,790\n[Music]\n\n" +
                "2\n00:00:02,800 --> 00:00:05,800\nWe're no strangers to\n\n" +
                "3\n00:00:05,800 --> 00:00:09,950\nlove. You know the rules\n",
        )
    }

    @Test
    fun `bridging cues alone and silence give no file`() {
        assertThat(srtText(listOf(segment(0, 10, "Blink")), isAutoGenerated = false)).isNull()
        assertThat(srtText(emptyList(), isAutoGenerated = true)).isNull()
    }
}
