package io.github.aedev.flow.data.video.downloader.subtitle

import androidx.media3.extractor.text.CuesWithTiming
import androidx.media3.extractor.text.SubtitleParser
import androidx.media3.extractor.text.subrip.SubripParser
import androidx.test.ext.junit.runners.AndroidJUnit4
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith

/**
 * On a device: Media3's WebVTT and SubRip parsers call `android.text.TextUtils`, which a plain JVM
 * test only stubs, so the round trip through the real parsers runs here.
 */
@RunWith(AndroidJUnit4::class)
class SrtTextRoundTripTest {
    private val authored =
        """
        WEBVTT

        00:00:01.000 --> 00:00:03.500
        First line
        with a second row

        00:01:05.250 --> 00:01:07.000
        <i>Styled</i> text
        """.trimIndent()

    // Shaped like YouTube's speech-recognised WebVTT: each cue repeats the line before it, with
    // word timings, a 10 ms cue bridges every pair, and "empty" lines inside a cue hold one space.
    private val autoGenerated =
        listOf(
            "WEBVTT",
            "Kind: captions",
            "Language: en",
            "",
            "00:00:00.320 --> 00:00:02.790 align:start position:0%",
            " ",
            "[Music]",
            "",
            "00:00:02.790 --> 00:00:02.800 align:start position:0%",
            " ",
            " ",
            "",
            "00:00:02.800 --> 00:00:05.790 align:start position:0%",
            " ",
            "We're<00:00:03.039><c> no</c><00:00:03.359><c> strangers</c><00:00:03.840><c> to</c>",
            "",
            "00:00:05.790 --> 00:00:05.800 align:start position:0%",
            "We're no strangers to",
            " ",
            "",
            "00:00:05.800 --> 00:00:09.950 align:start position:0%",
            "We're no strangers to",
            "love.<00:00:06.800><c> You</c><00:00:07.039><c> know</c><00:00:07.279><c> the</c><00:00:07.600><c> rules</c>",
            "",
        ).joinToString("\n")

    @Test
    fun authoredTrackKeepsItsLinesAndTimesAndReadsBackAsSubrip() {
        val srt = vttToSrt(authored.toByteArray(), isAutoGenerated = false)!!

        assertTrue(srt.startsWith("1\n00:00:01,000 --> 00:00:03,500\nFirst line\nwith a second row\n"))
        assertTrue(srt.contains("2\n00:01:05,250 --> 00:01:07,000\nStyled text\n"))
        assertEquals(listOf("First line\nwith a second row", "Styled text"), texts(parseSrt(srt)))
    }

    @Test
    fun speechRecognisedTrackShowsEachLineOnceForAsLongAsItIsSpoken() {
        val cues = parseSrt(vttToSrt(autoGenerated.toByteArray(), isAutoGenerated = true)!!)

        assertEquals(listOf("[Music]", "We're no strangers to", "love. You know the rules"), texts(cues))
        assertEquals(2_800_000L, cues[1].startTimeUs)
        assertEquals(5_800_000L, cues[1].endTimeUs)
    }

    @Test
    fun trackWithoutTextOrNotWebvttGivesNoFile() {
        assertNull(vttToSrt("WEBVTT\n\n".toByteArray(), isAutoGenerated = false))
        assertNull(vttToSrt("<timedtext/>".toByteArray(), isAutoGenerated = false))
    }

    private fun texts(segments: List<CuesWithTiming>): List<String> =
        segments.map {
            it.cues
                .single()
                .text
                .toString()
        }

    private fun parseSrt(srt: String): List<CuesWithTiming> {
        val out = mutableListOf<CuesWithTiming>()
        SubripParser().parse(srt.toByteArray(), SubtitleParser.OutputOptions.allCues()) { out += it }
        return out.filter { it.cues.isNotEmpty() }
    }
}
