package io.github.aedev.flow.player.subtitle

import io.github.aedev.flow.player.state.SubtitleOption
import io.github.aedev.flow.player.state.SubtitleOrigin
import io.github.aedev.flow.player.stream.CaptionTrackResolver

/** Whether the player turns captions on by itself, and in which language. */
data class SubtitleAutoPolicy(
    val enabled: Boolean,
    val languageTag: String?,
) {
    companion object {
        val OFF = SubtitleAutoPolicy(enabled = false, languageTag = null)
    }
}

internal object SubtitleChoice {
    /**
     * The track captions open on: the preferred language, else a human-authored track, else the
     * first one. Forced tracks never qualify, they carry only a few lines.
     */
    fun preferred(
        options: List<SubtitleOption>,
        languageTag: String?,
    ): SubtitleOption? {
        val candidates = options.filterNot { it.isForced }
        return CaptionTrackResolver.bestMatch(
            candidates = candidates,
            languageTag = languageTag,
            tagOf = { it.language },
            isAutoGenerated = { it.isAutoGenerated || it.isTranslated },
        ) ?: candidates.firstOrNull { !it.isAutoGenerated && !it.isTranslated }
            ?: candidates.firstOrNull()
    }

    /**
     * The track shown while nobody has picked one for this video: the preferred one when captions
     * turn on automatically. Otherwise, as other players do, a subtitle file someone put with the
     * video, in the preferred language when there are several, else a forced track.
     */
    fun automatic(
        options: List<SubtitleOption>,
        policy: SubtitleAutoPolicy,
    ): SubtitleOption? =
        preferred(options, policy.languageTag).takeIf { policy.enabled }
            ?: preferred(options.filter { it.origin == SubtitleOrigin.FILE }, policy.languageTag)
            ?: options.firstOrNull { it.isForced }
}
