package io.github.aedev.flow.data.video.downloader.subtitle

import android.util.Log
import androidx.media3.common.MimeTypes
import io.github.aedev.flow.data.local.PlayerPreferences
import io.github.aedev.flow.data.local.dao.DownloadDao
import io.github.aedev.flow.data.video.OfflineSubtitleStore
import io.github.aedev.flow.data.video.VideoDownloadManager
import io.github.aedev.flow.data.video.downloader.request.DownloadRequest
import io.github.aedev.flow.data.video.downloader.request.DownloadSubtitle
import io.github.aedev.flow.data.video.storage.DownloadFiles
import io.github.aedev.flow.data.video.storage.DownloadPlacement
import io.github.aedev.flow.data.video.storage.PlacedFile
import io.github.aedev.flow.player.stream.CaptionTrackResolver
import io.github.aedev.flow.player.stream.ResolvedCaption
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.withContext
import java.io.File
import java.net.URI
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Saves a finished video's chosen caption track as `Title.en.srt` beside it, where other players
 * and Flow's Local media find it. The track comes from the copy Flow already stored for offline
 * playback, so only a machine translation needs the network. Never fails the download.
 */
@Singleton
class DownloadSubtitleFile
    @Inject
    constructor(
        private val store: OfflineSubtitleStore,
        private val placement: DownloadPlacement,
        private val downloads: VideoDownloadManager,
        private val downloadDao: DownloadDao,
        private val preferences: PlayerPreferences,
    ) {
        /** @param known the video's WebVTT tracks from the download's own player response. */
        suspend fun writeBeside(
            request: DownloadRequest,
            placed: PlacedFile,
            known: List<ResolvedCaption> = emptyList(),
        ): DownloadRequest {
            val chosen = request.subtitle
            val wanted = chosen ?: settingChoice() ?: return request
            if (wanted.isOff) return request
            val (caption, vtt) =
                trackText(request.videoId, wanted, known, allowTranslation = chosen == null)
                    ?: return request.also { Log.d(TAG, "${request.videoId}: no ${wanted.languageTag} caption track to save") }
            val srt = vttToSrt(vtt.toByteArray(), caption.isAutoGenerated) ?: return request
            val name = "${placed.fileName.substringBeforeLast('.')}.${caption.languageTag}.srt"
            val path = placement.placeBeside(placed, request, name, srt) ?: return request
            if (!DownloadFiles.isDocument(path)) downloads.scanFile(path, MimeTypes.APPLICATION_SUBRIP)
            val updated = request.copy(subtitleFile = path)
            downloadDao.updateRequest(request.videoId, updated.encode())
            return updated
        }

        private suspend fun settingChoice(): DownloadSubtitle? {
            if (!preferences.downloadSubtitleFile.first()) return null
            val language =
                preferences.preferredSubtitleLanguage
                    .first()
                    .takeIf { it.isNotBlank() && it != CaptionTrackResolver.NO_PREFERRED_LANGUAGE }
            return DownloadSubtitle(language ?: DownloadSubtitle.ANY_LANGUAGE)
        }

        private suspend fun trackText(
            videoId: String,
            wanted: DownloadSubtitle,
            known: List<ResolvedCaption>,
            allowTranslation: Boolean,
        ): Pair<ResolvedCaption, String>? {
            pickDownloadCaption(store.load(videoId), wanted)?.let { stored ->
                readStored(stored.url)?.let { return stored to it }
            }
            val translateTo = wanted.languageTag.takeUnless { it == DownloadSubtitle.ANY_LANGUAGE }
            val online = known.ifEmpty { store.resolveOnline(videoId, translateTo) }
            val caption =
                pickDownloadCaption(online, wanted)
                    ?: pickDownloadCaption(online, wanted.copy(translated = true)).takeIf { allowTranslation }
                    ?: return null
            return store.fetchVtt(caption.url)?.let { caption to it }
        }

        private suspend fun readStored(url: String): String? =
            withContext(Dispatchers.IO) { runCatching { File(URI(url)).readText() }.getOrNull() }

        private companion object {
            const val TAG = "DownloadSubtitleFile"
        }
    }

/**
 * The track [wanted] names among [captions]: the same language and kind, else the closest
 * language, with [DownloadSubtitle.ANY_LANGUAGE] taking the first authored track.
 */
internal fun pickDownloadCaption(
    captions: List<ResolvedCaption>,
    wanted: DownloadSubtitle,
): ResolvedCaption? {
    if (wanted.isOff) return null
    val pool = captions.filter { it.isTranslated == wanted.translated }
    if (wanted.languageTag == DownloadSubtitle.ANY_LANGUAGE) return pool.firstOrNull { !it.isAutoGenerated } ?: pool.firstOrNull()
    return pool.firstOrNull { it.languageTag.equals(wanted.languageTag, ignoreCase = true) && it.isAutoGenerated == wanted.autoGenerated }
        ?: CaptionTrackResolver.bestMatch(pool, wanted.languageTag, tagOf = { it.languageTag }, isAutoGenerated = { it.isAutoGenerated })
}
