package io.github.aedev.flow.data.video.downloader.subtitle

import androidx.annotation.OptIn
import androidx.media3.common.util.UnstableApi
import androidx.media3.extractor.text.CuesWithTiming
import androidx.media3.extractor.text.SubtitleParser
import androidx.media3.extractor.text.webvtt.WebvttParser
import io.github.aedev.flow.player.subtitle.toRollingCaptionText
import java.util.Locale

private data class SrtLine(
    val startUs: Long,
    val endUs: Long,
    val text: String,
)

/**
 * A WebVTT caption track as SubRip text, which far more players and TVs read. Media3 parses the
 * WebVTT; it ships no subtitle writer, so only the SubRip text is written here. Null when the
 * track is not WebVTT or holds no text.
 */
@OptIn(UnstableApi::class)
internal fun vttToSrt(
    vtt: ByteArray,
    isAutoGenerated: Boolean,
): String? {
    val segments = mutableListOf<CuesWithTiming>()
    try {
        WebvttParser().parse(vtt, SubtitleParser.OutputOptions.allCues()) { segments += it }
    } catch (_: Exception) {
        return null
    }
    return srtText(segments, isAutoGenerated)
}

/**
 * Timed caption segments as SubRip text. Speech-recognised tracks repeat each line in the next cue
 * and add 10 ms bridging cues between them, so for those only the words each segment adds are
 * kept, and a line is shown once for as long as it is spoken.
 */
@OptIn(UnstableApi::class)
internal fun srtText(
    segments: List<CuesWithTiming>,
    isAutoGenerated: Boolean,
): String? {
    val lines = mutableListOf<SrtLine>()
    segments.forEach { segment ->
        val text =
            if (isAutoGenerated) {
                segment.cues.toRollingCaptionText()
            } else {
                segment.cues
                    .mapNotNull { cue -> cue.text?.toString()?.trim() }
                    .filter { it.isNotEmpty() }
                    .joinToString("\n")
            }
        if (text.isNullOrBlank()) return@forEach
        val last = lines.lastOrNull()
        if (last != null && last.text == text && segment.startTimeUs - last.endUs <= JOIN_GAP_US) {
            lines[lines.lastIndex] = last.copy(endUs = segment.endTimeUs)
        } else if (segment.endTimeUs - segment.startTimeUs >= MIN_LINE_US) {
            lines += SrtLine(segment.startTimeUs, segment.endTimeUs, text)
        }
    }
    if (lines.isEmpty()) return null
    return lines
        .mapIndexed { index, line -> "${index + 1}\n${srtTime(line.startUs)} --> ${srtTime(line.endUs)}\n${line.text}\n" }
        .joinToString("\n")
}

private fun srtTime(timeUs: Long): String {
    val totalMs = timeUs / 1_000
    return String.format(
        Locale.ROOT,
        "%02d:%02d:%02d,%03d",
        totalMs / 3_600_000,
        totalMs / 60_000 % 60,
        totalMs / 1_000 % 60,
        totalMs % 1_000,
    )
}

private const val MIN_LINE_US = 50_000L
private const val JOIN_GAP_US = 100_000L
