package io.github.aedev.flow.ui.components.shared

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource
import io.github.aedev.flow.R
import io.github.aedev.flow.data.local.PlayerPreferences
import io.github.aedev.flow.data.video.downloader.request.DownloadSubtitle
import io.github.aedev.flow.player.state.SubtitleOption
import io.github.aedev.flow.player.state.SubtitleOrigin
import io.github.aedev.flow.player.stream.CaptionTrackResolver
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.launch

/** The video's own online caption tracks, the only ones a download can save as a file. */
internal fun downloadableSubtitles(options: List<SubtitleOption>): List<SubtitleOption> =
    options.filter {
        it.origin ==
            SubtitleOrigin.ONLINE
    }

/** The track the dialog opens on: the language chosen last time, if this video has it. */
internal fun defaultDownloadSubtitle(
    options: List<SubtitleOption>,
    lastLanguage: String?,
): SubtitleOption? {
    val language = lastLanguage?.takeIf { it.isNotBlank() } ?: return null
    return CaptionTrackResolver.bestMatch(
        candidates = options,
        languageTag = language,
        tagOf = { it.language },
        isAutoGenerated = { it.isAutoGenerated || it.isTranslated },
    )
}

internal fun SubtitleOption.toDownloadSubtitle(): DownloadSubtitle =
    DownloadSubtitle(languageTag = language, autoGenerated = isAutoGenerated, translated = isTranslated)

@Composable
internal fun downloadSubtitleLabel(option: SubtitleOption?): String {
    if (option == null) return stringResource(R.string.off)
    val kind =
        when {
            option.isTranslated -> stringResource(R.string.subtitle_translated)
            option.isAutoGenerated -> stringResource(R.string.quality_auto)
            else -> return option.label
        }
    return stringResource(R.string.subtitle_auto_generated_template, option.label, kind)
}

// A dialog closes as its download starts, so the choice is saved outside its composition.
private val subtitleChoiceScope = CoroutineScope(SupervisorJob() + Dispatchers.IO)

/** Remembers the dialog's choice for the next download; blank for none. */
internal fun rememberDownloadSubtitleChoice(
    preferences: PlayerPreferences,
    option: SubtitleOption?,
) {
    subtitleChoiceScope.launch { preferences.setLastDownloadSubtitleLanguage(option?.language.orEmpty()) }
}

/** The dialog's Subtitles row: Off, or one of the video's tracks. */
@Composable
internal fun DownloadSubtitleRow(
    options: List<SubtitleOption>,
    selected: SubtitleOption?,
    onSelect: (SubtitleOption?) -> Unit,
) {
    val offLabel = stringResource(R.string.off)
    DownloadDropdownRow(
        label = stringResource(R.string.filter_subtitles),
        value = downloadSubtitleLabel(selected),
        options = listOf(offLabel to { onSelect(null) }) + options.map { option -> downloadSubtitleLabel(option) to { onSelect(option) } },
    )
}
