package io.github.aedev.flow.player.subtitle

import com.google.common.truth.Truth.assertThat
import io.github.aedev.flow.player.state.SubtitleOption
import io.github.aedev.flow.player.state.SubtitleOrigin
import org.junit.Test

/** How a remembered language tag and the automatic policy resolve against a video's tracks. */
class SubtitleChoiceTest {
    private fun option(
        language: String,
        auto: Boolean = false,
        translated: Boolean = false,
        forced: Boolean = false,
    ) = SubtitleOption(
        url = "https://example.invalid/$language",
        language = language,
        label = language,
        isAutoGenerated = auto,
        isTranslated = translated,
        isForced = forced,
    )

    private fun indexOfLanguage(
        subtitles: List<SubtitleOption>,
        languageTag: String?,
    ): Int = subtitles.indexOf(SubtitleChoice.preferred(subtitles, languageTag))

    @Test
    fun `an exact tag match returns its index`() {
        val subtitles = listOf(option("fr"), option("en"), option("de"))

        assertThat(indexOfLanguage(subtitles, "en")).isEqualTo(1)
        assertThat(indexOfLanguage(subtitles, "de")).isEqualTo(2)
    }

    @Test
    fun `the match is case insensitive and tolerates underscores`() {
        val subtitles = listOf(option("fr"), option("en-US"))

        assertThat(indexOfLanguage(subtitles, "EN-us")).isEqualTo(1)
        assertThat(indexOfLanguage(subtitles, "en_GB")).isEqualTo(1)
    }

    @Test
    fun `a regional tag falls back to the base language`() {
        val subtitles = listOf(option("fr"), option("en"))

        assertThat(indexOfLanguage(subtitles, "en-US")).isEqualTo(1)
        assertThat(indexOfLanguage(subtitles, "fr-CA")).isEqualTo(0)
    }

    @Test
    fun `an exact regional match beats a base language match`() {
        val subtitles = listOf(option("en"), option("en-GB"), option("en-US"))

        assertThat(indexOfLanguage(subtitles, "en-US")).isEqualTo(2)
        assertThat(indexOfLanguage(subtitles, "en-GB")).isEqualTo(1)
    }

    @Test
    fun `a human authored track beats an auto generated one for the same language`() {
        val subtitles = listOf(option("en", auto = true), option("en"))

        assertThat(indexOfLanguage(subtitles, "en")).isEqualTo(1)
    }

    @Test
    fun `a machine translated track counts as auto generated`() {
        val subtitles = listOf(option("en", translated = true), option("en"))

        assertThat(indexOfLanguage(subtitles, "en")).isEqualTo(1)
    }

    @Test
    fun `exactness outranks authorship`() {
        // Pins current behaviour: the tag comparison is the primary key, so an auto-generated exact
        // regional match wins over a human-authored base-language track.
        val subtitles = listOf(option("en-US", auto = true), option("en"))

        assertThat(indexOfLanguage(subtitles, "en-US")).isEqualTo(0)
        assertThat(indexOfLanguage(subtitles, "en")).isEqualTo(1)
    }

    @Test
    fun `the first of two equally ranked tracks wins`() {
        val subtitles = listOf(option("en", auto = true), option("en", auto = true))

        assertThat(indexOfLanguage(subtitles, "en")).isEqualTo(0)
    }

    @Test
    fun `without a match an authored track is next, then the first track`() {
        assertThat(indexOfLanguage(listOf(option("fr", auto = true), option("de")), "en")).isEqualTo(1)
        assertThat(indexOfLanguage(listOf(option("fr", auto = true), option("de", translated = true)), "en")).isEqualTo(0)
        assertThat(indexOfLanguage(listOf(option("en")), "none")).isEqualTo(0)
        assertThat(indexOfLanguage(emptyList(), "en")).isEqualTo(-1)
    }

    @Test
    fun `a forced track is never the preferred one`() {
        val subtitles = listOf(option("en", forced = true), option("en", auto = true))

        assertThat(indexOfLanguage(subtitles, "en")).isEqualTo(1)
        assertThat(SubtitleChoice.preferred(listOf(option("en", forced = true)), "en")).isNull()
    }

    @Test
    fun `automatic captions pick the preferred track, and only a forced one when they are off`() {
        val forced = option("ja", forced = true)
        val english = option("en")

        assertThat(
            SubtitleChoice.automatic(listOf(forced, english), SubtitleAutoPolicy(enabled = true, languageTag = "en")),
        ).isEqualTo(english)
        assertThat(SubtitleChoice.automatic(listOf(forced, english), SubtitleAutoPolicy.OFF)).isEqualTo(forced)
        assertThat(SubtitleChoice.automatic(listOf(english), SubtitleAutoPolicy.OFF)).isNull()
    }

    @Test
    fun `a subtitle file with a device video shows without automatic captions`() {
        val file =
            SubtitleOption(
                url = "file:///Movie.en.srt",
                language = "en",
                label = "English",
                isAutoGenerated = false,
                origin = SubtitleOrigin.FILE,
            )
        val fileFr =
            SubtitleOption(
                url = "file:///Movie.fr.srt",
                language = "fr",
                label = "French",
                isAutoGenerated = false,
                origin = SubtitleOrigin.FILE,
            )
        val embedded =
            SubtitleOption(
                url = "embedded:3",
                language = "en",
                label = "English",
                isAutoGenerated = false,
                origin = SubtitleOrigin.EMBEDDED,
            )

        assertThat(SubtitleChoice.automatic(listOf(embedded, file), SubtitleAutoPolicy.OFF)).isEqualTo(file)
        assertThat(
            SubtitleChoice.automatic(listOf(file, fileFr), SubtitleAutoPolicy(enabled = false, languageTag = "fr")),
        ).isEqualTo(fileFr)
        assertThat(SubtitleChoice.automatic(listOf(embedded), SubtitleAutoPolicy.OFF)).isNull()
    }
}
