package io.github.aedev.flow.player.subtitle

import androidx.media3.common.C
import androidx.media3.common.Format
import androidx.media3.common.MimeTypes
import androidx.media3.common.TrackGroup
import androidx.media3.common.Tracks
import com.google.common.truth.Truth.assertThat
import io.github.aedev.flow.player.media.MediaLoader
import io.github.aedev.flow.player.state.SubtitleOrigin
import io.github.aedev.flow.player.stream.CaptionFormat
import io.github.aedev.flow.player.stream.ResolvedCaption
import org.junit.Test

class SubtitleTracksTest {
    private fun online(
        language: String,
        signature: String = "a",
    ) = ResolvedCaption(
        language,
        isAutoGenerated = false,
        url = "https://yt/timedtext?lang=$language&sig=$signature",
        format = CaptionFormat.SRV3,
    )

    private val englishOn = SubtitleAutoPolicy(enabled = true, languageTag = "en")

    @Test
    fun `automatic captions follow the policy until someone picks`() {
        val tracks = SubtitleTracks()
        tracks.load("v1", listOf(online("de"), online("en")), acceptsEmbedded = false)

        assertThat(tracks.selected).isNull()
        assertThat(tracks.setPolicy(englishOn)).isTrue()
        assertThat(tracks.selected?.language).isEqualTo("en")
    }

    @Test
    fun `a pick survives the same video coming back under new signed urls`() {
        val tracks = SubtitleTracks()
        tracks.setPolicy(englishOn)
        tracks.load("v1", listOf(online("de"), online("en")), acceptsEmbedded = false)
        tracks.select(tracks.options.first { it.language == "de" }.url)

        tracks.load("v1", emptyList(), acceptsEmbedded = false)
        tracks.load("v1", listOf(online("de", signature = "b"), online("en", signature = "b")), acceptsEmbedded = false)

        assertThat(tracks.selected?.url).isEqualTo(online("de", signature = "b").url)
        assertThat(tracks.setPolicy(SubtitleAutoPolicy.OFF)).isFalse()
    }

    @Test
    fun `turning captions off sticks for the video and a new video starts fresh`() {
        val tracks = SubtitleTracks()
        tracks.setPolicy(englishOn)
        tracks.load("v1", listOf(online("en")), acceptsEmbedded = false)
        tracks.select(null)
        tracks.load("v1", listOf(online("en", signature = "b")), acceptsEmbedded = false)

        assertThat(tracks.selected).isNull()

        tracks.load("v2", listOf(online("en")), acceptsEmbedded = false)
        assertThat(tracks.selected?.language).isEqualTo("en")
    }

    @Test
    fun `tracks inside a device file join the list and a forced one shows with captions off`() {
        val tracks = SubtitleTracks()
        tracks.load("local_1", emptyList(), acceptsEmbedded = true)

        val changed = tracks.onTracksChanged(textTracks(format("3", "en", forced = false), format("4", "ja", forced = true)))

        assertThat(changed).isTrue()
        assertThat(tracks.options.map { it.url }).containsExactly("embedded:3", "embedded:4").inOrder()
        assertThat(tracks.options.all { it.origin == SubtitleOrigin.EMBEDDED }).isTrue()
        assertThat(tracks.selected?.url).isEqualTo("embedded:4")
        assertThat(tracks.onTracksChanged(textTracks(format("3", "en", forced = false), format("4", "ja", forced = true)))).isFalse()
    }

    @Test
    fun `flow's own caption tracks and online videos never list embedded tracks`() {
        val tracks = SubtitleTracks()
        tracks.load("local_1", emptyList(), acceptsEmbedded = true)
        assertThat(tracks.onTracksChanged(textTracks(format(MediaLoader.subtitleTrackId(0), "en", forced = false)))).isFalse()
        // A merging source prefixes each format id with its source's position.
        assertThat(tracks.onTracksChanged(textTracks(format("1:${MediaLoader.subtitleTrackId(3)}", "en", forced = false)))).isFalse()

        tracks.load("v1", emptyList(), acceptsEmbedded = false)
        assertThat(tracks.onTracksChanged(textTracks(format("3", "en", forced = false)))).isFalse()
        assertThat(tracks.options).isEmpty()
    }

    @Test
    fun `caption indexes are read back from prefixed format ids`() {
        assertThat(MediaLoader.subtitleTrackIndex("2:flow-subtitle-12")).isEqualTo(12)
        assertThat(MediaLoader.subtitleTrackIndex(MediaLoader.subtitleTrackId(0))).isEqualTo(0)
        assertThat(MediaLoader.subtitleTrackIndex("3")).isNull()
        assertThat(MediaLoader.subtitleTrackIndex(null)).isNull()
    }

    private fun format(
        id: String,
        language: String,
        forced: Boolean,
    ): Format =
        Format
            .Builder()
            .setId(id)
            .setSampleMimeType(MimeTypes.APPLICATION_SUBRIP)
            .setLanguage(language)
            .setSelectionFlags(if (forced) C.SELECTION_FLAG_FORCED else 0)
            .build()

    private fun textTracks(vararg formats: Format): Tracks =
        Tracks(
            formats.map { format ->
                Tracks.Group(TrackGroup(format), false, intArrayOf(C.FORMAT_HANDLED), booleanArrayOf(false))
            },
        )
}
