package io.github.aedev.flow.data.video

import android.content.Context
import android.util.Log
import dagger.hilt.android.qualifiers.ApplicationContext
import io.github.aedev.flow.innertube.YouTube
import io.github.aedev.flow.innertube.models.YouTubeClient
import io.github.aedev.flow.player.stream.CaptionFormat
import io.github.aedev.flow.player.stream.CaptionTrackResolver
import io.github.aedev.flow.player.stream.ResolvedCaption
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import okhttp3.Request
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Keeps a downloaded video's caption tracks on disk beside the download.
 *
 * Caption URLs are signed and expire within hours, so a download that only remembers the URL has
 * no captions the next time the app starts. The tracks themselves are a few KB of text, so they
 * are fetched once at download time and replayed from local files afterwards — which also makes
 * captions work with no network at all.
 */
@Singleton
class OfflineSubtitleStore
    @Inject
    constructor(
        @ApplicationContext private val context: Context,
        private val httpClient: OkHttpClient,
    ) {
        private val rootDir: File
            get() = File(context.filesDir, ROOT_DIR)

        private fun videoDir(videoId: String) = File(rootDir, videoId.sanitized())

        /**
         * Resolve and store the video's native caption tracks. Auto-translations are skipped: they
         * are derived from a track we already keep and would multiply the stored files by twenty.
         *
         * @param known WebVTT tracks the caller already resolved, which spares a player request.
         */
        suspend fun saveForVideo(
            videoId: String,
            known: List<ResolvedCaption> = emptyList(),
        ): Int =
            withContext(Dispatchers.IO) {
                try {
                    val captions = known.filter { it.format == CaptionFormat.VTT }.ifEmpty { resolveCaptionTracks(videoId) }
                    if (captions.isEmpty()) {
                        Log.d(TAG, "No caption tracks to store for $videoId")
                        markResolvedWithoutTracks(videoId)
                        return@withContext 0
                    }
                    save(videoId, captions)
                } catch (e: Exception) {
                    Log.w(TAG, "Storing captions for $videoId failed: ${e.message}")
                    0
                }
            }

        suspend fun save(
            videoId: String,
            captions: List<ResolvedCaption>,
        ): Int =
            withContext(Dispatchers.IO) {
                val dir = videoDir(videoId)
                if (!dir.exists() && !dir.mkdirs()) {
                    Log.w(TAG, "Could not create caption dir for $videoId")
                    return@withContext 0
                }

                val stored = JSONArray()
                captions
                    .filterNot { it.isTranslated }
                    .forEach { caption ->
                        val fileName = captionFileName(caption.languageTag, caption.isAutoGenerated)
                        val target = File(dir, fileName)
                        if (!downloadTo(caption.url, target)) return@forEach
                        stored.put(
                            JSONObject().apply {
                                put(KEY_LANGUAGE, caption.languageTag)
                                put(KEY_AUTO_GENERATED, caption.isAutoGenerated)
                                put(KEY_FILE, fileName)
                            },
                        )
                    }

                if (stored.length() == 0) {
                    dir.deleteRecursively()
                    return@withContext 0
                }

                File(dir, INDEX_FILE).writeText(JSONObject().put(KEY_TRACKS, stored).toString())
                Log.d(TAG, "Stored ${stored.length()} offline caption track(s) for $videoId")
                stored.length()
            }

        /** Whether captions were already looked up for [videoId], including a lookup that found none. */
        suspend fun isResolved(videoId: String): Boolean = withContext(Dispatchers.IO) { File(videoDir(videoId), INDEX_FILE).isFile }

        private fun markResolvedWithoutTracks(videoId: String) {
            val dir = videoDir(videoId)
            if (!dir.exists() && !dir.mkdirs()) return
            File(dir, INDEX_FILE).writeText(JSONObject().put(KEY_TRACKS, JSONArray()).toString())
        }

        /** Caption tracks previously stored for [videoId], as file-backed captions. */
        suspend fun load(videoId: String): List<ResolvedCaption> =
            withContext(Dispatchers.IO) {
                val dir = videoDir(videoId)
                val index = File(dir, INDEX_FILE)
                if (!index.isFile) return@withContext emptyList()

                try {
                    val tracks = JSONObject(index.readText()).optJSONArray(KEY_TRACKS) ?: return@withContext emptyList()
                    (0 until tracks.length()).mapNotNull { position ->
                        val entry = tracks.optJSONObject(position) ?: return@mapNotNull null
                        val file = File(dir, entry.optString(KEY_FILE))
                        if (!file.isFile) return@mapNotNull null
                        ResolvedCaption(
                            languageTag = entry.optString(KEY_LANGUAGE),
                            isAutoGenerated = entry.optBoolean(KEY_AUTO_GENERATED),
                            url = file.toURI().toString(),
                            format = CaptionFormat.VTT,
                        )
                    }
                } catch (e: Exception) {
                    Log.w(TAG, "Reading offline captions for $videoId failed: ${e.message}")
                    emptyList()
                }
            }

        suspend fun delete(videoId: String) =
            withContext(Dispatchers.IO) {
                videoDir(videoId).deleteRecursively()
                Unit
            }

        /**
         * The video's caption tracks as fresh WebVTT URLs, with a machine translation into
         * [translateTo] when the video has no track in it. Caption URLs expire within hours, so
         * nothing that waited in a queue can use an old one.
         */
        suspend fun resolveOnline(
            videoId: String,
            translateTo: String? = null,
        ): List<ResolvedCaption> = withContext(Dispatchers.IO) { resolveCaptionTracks(videoId, translateTo) }

        /** The WebVTT body at [url], or null when the fetch fails or returns something else. */
        suspend fun fetchVtt(url: String): String? = withContext(Dispatchers.IO) { fetchVttBody(url) }

        private suspend fun resolveCaptionTracks(
            videoId: String,
            translateTo: String? = null,
        ): List<ResolvedCaption> {
            CAPTION_CLIENTS.forEach { client ->
                val response = YouTube.player(videoId, client = client).getOrNull()
                // VTT, not the default srv3: downloadTo() below validates and stores the raw
                // WEBVTT body as-is, and offline playback only ever builds VTT captions.
                val captions =
                    response
                        ?.let {
                            CaptionTrackResolver.resolve(
                                it,
                                format = CaptionFormat.VTT,
                                translateTo = translateTo,
                            )
                        }.orEmpty()
                if (captions.isNotEmpty()) return captions
            }
            return emptyList()
        }

        private fun downloadTo(
            url: String,
            target: File,
        ): Boolean {
            val body = fetchVttBody(url) ?: return false
            target.writeText(body)
            return true
        }

        private fun fetchVttBody(url: String): String? =
            try {
                httpClient
                    .newCall(Request.Builder().url(url).build())
                    .execute()
                    .use { response ->
                        val body = response.body?.string()
                        if (!response.isSuccessful || body.isNullOrBlank() || !body.startsWith(VTT_MAGIC)) {
                            Log.w(TAG, "Caption fetch rejected (${response.code})")
                            null
                        } else {
                            body
                        }
                    }
            } catch (e: Exception) {
                Log.w(TAG, "Caption fetch failed: ${e.message}")
                null
            }

        private fun captionFileName(
            languageTag: String,
            autoGenerated: Boolean,
        ): String = "${languageTag.sanitized()}${if (autoGenerated) ".auto" else ""}.vtt"

        private fun String.sanitized(): String = replace(Regex("[^A-Za-z0-9_.-]"), "_")

        companion object {
            private const val TAG = "OfflineSubtitleStore"
            private const val ROOT_DIR = "offline_subtitles"
            private const val INDEX_FILE = "index.json"
            private const val KEY_TRACKS = "tracks"
            private const val KEY_LANGUAGE = "language"
            private const val KEY_AUTO_GENERATED = "autoGenerated"
            private const val KEY_FILE = "file"
            private const val VTT_MAGIC = "WEBVTT"

            private val CAPTION_CLIENTS = listOf(YouTubeClient.ANDROID_VR_NO_AUTH, YouTubeClient.MOBILE)
        }
    }
