package io.github.aedev.flow.player.state

data class EnhancedPlayerState(
    val currentVideoId: String? = null,
    val isPlaying: Boolean = false,
    val playWhenReady: Boolean = false,
    val isBuffering: Boolean = false,
    val isPrepared: Boolean = false,
    val hasEnded: Boolean = false,
    val currentQuality: Int = 0,
    val effectiveQuality: Int = 0,
    val currentQualityKey: String? = null,
    val currentAudioTrack: Int = 0,
    val sourceVideoAspectRatio: Float? = null,
    val availableQualities: List<QualityOption> = emptyList(),
    val availableAudioTracks: List<AudioTrackOption> = emptyList(),
    val availableSubtitles: List<SubtitleOption> = emptyList(),
    /** The [SubtitleOption.url] of the track on screen, or null when captions are off. */
    val selectedSubtitleUrl: String? = null,
    /** How far captions are shifted, in milliseconds: positive shows them later. */
    val subtitleOffsetMs: Long = 0L,
    val error: String? = null,
    val recoveryAttempted: Boolean = false,
    val playbackSpeed: Float = 1.0f,
    val isSkipSilenceEnabled: Boolean = false,
    val isStableVolumeEnabled: Boolean = false,
    val bufferedPercentage: Float = 0f,
    val hasNext: Boolean = false,
    val hasPrevious: Boolean = false,
    val queueTitle: String? = null,
    val queueSize: Int = 0,
    val isQueueLooping: Boolean = false,
    val isQueueShuffled: Boolean = false,
    val isLooping: Boolean = false,
    val isLive: Boolean = false,
    val isAtLiveEdge: Boolean = false,
    val liveDurationMs: Long = 0L,
)

/** A video that played to its end, and the length it ended at. */
data class PlaybackCompletion(
    val videoId: String,
    val durationMs: Long,
)

// video quality option for the quality selector.
data class QualityOption(
    val height: Int,
    val label: String,
    val bitrate: Long,
    val codecKey: String = "",
    val streamKey: String? = null,
)

// audio track option for the audio selector.
data class AudioTrackOption(
    val index: Int,
    val label: String,
    val language: String,
    val bitrate: Long,
)

/** Where a subtitle track lives, which the picker names under the track. */
enum class SubtitleOrigin {
    ONLINE,
    FILE,
    EMBEDDED,
}

/**
 * One row of the subtitle picker. [url] identifies the track: its address, or an `embedded:` key for
 * a track inside the video file, which has none. [isForced] marks a track the file flags as forced:
 * only the lines in a language other than the audio's.
 */
data class SubtitleOption(
    val url: String,
    val language: String,
    val label: String,
    val isAutoGenerated: Boolean,
    val isTranslated: Boolean = false,
    val origin: SubtitleOrigin = SubtitleOrigin.ONLINE,
    val isForced: Boolean = false,
    /** Where a file track lives, such as `Subs/English.srt`, shown under its name. */
    val detail: String? = null,
)
