package io.github.aedev.flow.player.stream

import io.github.aedev.flow.innertube.models.response.PlayerResponse
import io.github.aedev.flow.player.state.SubtitleOption
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/** A signed timedtext URL as YouTube serves it today — note the trailing `fmt=srv3`. */
private const val BASE_URL =
    "https://www.youtube.com/api/timedtext?v=abc&ei=XYZ&caps=asr&sparams=ip,ipbits,expire,v" +
        "&signature=DEADBEEF.0123&key=yt8&lang=en&fmt=srv3"

private fun tracklist(tracks: List<PlayerResponse.Captions.CaptionTrack>) =
    PlayerResponse.Captions.PlayerCaptionsTracklistRenderer(captionTracks = tracks)

private fun track(
    languageCode: String,
    kind: String? = null,
    baseUrl: String = BASE_URL,
) = PlayerResponse.Captions.CaptionTrack(
    baseUrl = baseUrl,
    languageCode = languageCode,
    kind = kind,
)

class CaptionTrackResolverTest {
    @Test
    fun `srv3 is requested by default for styled and positioned captions`() {
        val resolved = CaptionTrackResolver.resolveTracklist(tracklist(listOf(track("en"))))

        val url = resolved.single().url
        assertEquals("exactly one fmt parameter expected: $url", 1, url.split("fmt=").size - 1)
        assertTrue(url.endsWith("fmt=srv3"))
    }

    @Test
    fun `an explicit vtt format request is honoured, not duplicated`() {
        val resolved =
            CaptionTrackResolver.resolveTracklist(tracklist(listOf(track("en"))), format = CaptionFormat.VTT)

        val url = resolved.single().url
        assertFalse("srv3 must not survive: $url", url.contains("fmt=srv3"))
        assertEquals("exactly one fmt parameter expected: $url", 1, url.split("fmt=").size - 1)
        assertTrue(url.endsWith("fmt=vtt"))
    }

    @Test
    fun `signed parameters survive untouched so the url stays valid`() {
        val url = CaptionTrackResolver.resolveTracklist(tracklist(listOf(track("en")))).single().url

        assertTrue(url.contains("signature=DEADBEEF.0123"))
        assertTrue("commas in sparams must not be re-encoded: $url", url.contains("sparams=ip,ipbits,expire,v"))
        assertTrue(url.startsWith("https://www.youtube.com/api/timedtext?"))
    }

    @Test
    fun `machine translations are not offered`() {
        // YouTube throttles timedtext requests carrying &tlang= hard enough that the tracks are
        // dead more often than not, so the menu must not advertise them at all.
        val resolved = CaptionTrackResolver.resolveTracklist(tracklist(listOf(track("en"), track("de-DE"))))

        assertEquals(listOf("en", "de-DE"), resolved.map { it.languageTag })
        assertTrue(resolved.none { it.isTranslated })
        assertTrue("no tlang may reach the player: ${resolved.map { it.url }}", resolved.none { "tlang" in it.url })
    }

    @Test
    fun `an auto generated caption track is still marked as such`() {
        val resolved = CaptionTrackResolver.resolveTracklist(tracklist(listOf(track("en", kind = "asr"))))

        assertTrue(resolved.single().isAutoGenerated)
    }

    @Test
    fun `auto generated tracks stay on vtt even when srv3 is the default`() {
        // YouTube serves ASR srv3 as a roll-up of word-timed segments; the rolling caption bubble
        // rebuilds the current line from plain cues and cannot read that structure.
        val resolved =
            CaptionTrackResolver.resolveTracklist(tracklist(listOf(track("en"), track("en", kind = "asr"))))

        val authored = resolved.single { !it.isAutoGenerated }
        val auto = resolved.single { it.isAutoGenerated }

        assertEquals(CaptionFormat.SRV3, authored.format)
        assertTrue(authored.url.endsWith("fmt=srv3"))
        assertEquals(CaptionFormat.VTT, auto.format)
        assertTrue("ASR must not be requested as srv3: ${auto.url}", auto.url.endsWith("fmt=vtt"))
    }

    @Test
    fun `a stored region tag still matches the base language and prefers the human track`() {
        val options =
            listOf(
                SubtitleOption(url = "a", language = "pt-BR", label = "Portuguese", isAutoGenerated = true),
                SubtitleOption(url = "b", language = "pt-BR", label = "Portuguese", isAutoGenerated = false),
                SubtitleOption(url = "c", language = "en", label = "English", isAutoGenerated = false),
            )

        val match =
            CaptionTrackResolver.bestMatch(
                candidates = options,
                languageTag = "pt",
                tagOf = { it.language },
                isAutoGenerated = { it.isAutoGenerated },
            )

        assertEquals("b", match?.url)
    }

    @Test
    fun `no preference matches nothing`() {
        val options = listOf(SubtitleOption(url = "a", language = "en", label = "English", isAutoGenerated = false))

        assertNull(
            CaptionTrackResolver.bestMatch(
                candidates = options,
                languageTag = CaptionTrackResolver.NO_PREFERRED_LANGUAGE,
                tagOf = { it.language },
                isAutoGenerated = { it.isAutoGenerated },
            ),
        )
    }
}

private fun tracklistWithTranslations(
    tracks: List<PlayerResponse.Captions.CaptionTrack>,
    languages: List<String>,
) = PlayerResponse.Captions.PlayerCaptionsTracklistRenderer(
    captionTracks = tracks,
    translationLanguages =
        languages.map {
            PlayerResponse.Captions.TranslationLanguage(languageCode = it)
        },
)

private fun translatable(
    languageCode: String,
    kind: String? = null,
) = PlayerResponse.Captions.CaptionTrack(
    baseUrl = BASE_URL,
    languageCode = languageCode,
    kind = kind,
    isTranslatable = true,
)

class CaptionTrackAutoTranslationTest {
    @Test
    fun `a preferred language absent from the video is machine translated`() {
        val resolved =
            CaptionTrackResolver.resolveTracklist(
                tracklistWithTranslations(listOf(translatable("en")), listOf("es", "fr")),
                translateTo = "es",
            )

        assertEquals(2, resolved.size)
        val translated = resolved.last()
        assertEquals("es", translated.languageTag)
        assertTrue(translated.isTranslated)
        assertTrue(translated.url.contains("&tlang=es"))
    }

    @Test
    fun `only one translation is produced however many languages are offered`() {
        val resolved =
            CaptionTrackResolver.resolveTracklist(
                tracklistWithTranslations(listOf(translatable("en")), List(156) { "l$it" } + "es"),
                translateTo = "es",
            )

        assertEquals(2, resolved.size)
    }

    @Test
    fun `a language the video already carries is never translated`() {
        val resolved =
            CaptionTrackResolver.resolveTracklist(
                tracklistWithTranslations(listOf(translatable("en"), translatable("es")), listOf("es")),
                translateTo = "es",
            )

        assertEquals(2, resolved.size)
        assertFalse(resolved.any { it.isTranslated })
    }

    @Test
    fun `no preferred language means no translation`() {
        val resolved =
            CaptionTrackResolver.resolveTracklist(
                tracklistWithTranslations(listOf(translatable("en")), listOf("es")),
                translateTo = CaptionTrackResolver.NO_PREFERRED_LANGUAGE,
            )

        assertEquals(1, resolved.size)
    }

    @Test
    fun `a language the server does not offer is not invented`() {
        val resolved =
            CaptionTrackResolver.resolveTracklist(
                tracklistWithTranslations(listOf(translatable("en")), listOf("es")),
                translateTo = "ja",
            )

        assertEquals(1, resolved.size)
    }

    @Test
    fun `an untranslatable track cannot be the source`() {
        val resolved =
            CaptionTrackResolver.resolveTracklist(
                tracklistWithTranslations(listOf(track("en")), listOf("es")),
                translateTo = "es",
            )

        assertEquals(1, resolved.size)
    }

    @Test
    fun `the translated url carries exactly one fmt and one tlang`() {
        val resolved =
            CaptionTrackResolver.resolveTracklist(
                tracklistWithTranslations(listOf(translatable("en")), listOf("es")),
                translateTo = "es",
            )

        val url = resolved.last().url
        assertEquals("exactly one fmt expected: $url", 1, url.split("fmt=").size - 1)
        assertEquals("exactly one tlang expected: $url", 1, url.split("tlang=").size - 1)
    }

    @Test
    fun `an asr source forces the plain vtt form`() {
        val resolved =
            CaptionTrackResolver.resolveTracklist(
                tracklistWithTranslations(listOf(translatable("en", kind = "asr")), listOf("es")),
                translateTo = "es",
            )

        val translated = resolved.last()
        assertEquals(CaptionFormat.VTT, translated.format)
        assertTrue(translated.url.contains("fmt=vtt"))
    }
}
