package io.github.aedev.flow.player.stream

import androidx.media3.common.MimeTypes
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

class ResolvedCaptionTest {
    @Test
    fun `a translated caption is told apart by its tlang parameter`() {
        val base = "https://www.youtube.com/api/timedtext?v=x&lang=en&fmt=vtt"

        assertFalse(ResolvedCaption("en", isAutoGenerated = false, url = base, format = CaptionFormat.VTT).isTranslated)
        assertTrue(ResolvedCaption("es", isAutoGenerated = true, url = "$base&tlang=es", format = CaptionFormat.VTT).isTranslated)
    }

    @Test
    fun `subtitle file extensions map to the formats media3 reads`() {
        assertEquals(CaptionFormat.SRT, CaptionFormat.ofExtension("SRT"))
        assertEquals(CaptionFormat.SSA, CaptionFormat.ofExtension("ass"))
        assertEquals(CaptionFormat.TTML, CaptionFormat.ofExtension("dfxp"))
        assertEquals(MimeTypes.TEXT_VTT, CaptionFormat.ofExtension("vtt")?.mimeType)
        assertNull(CaptionFormat.ofExtension("sub"))
    }
}
