package io.github.aedev.flow.ui.components.shared

import com.google.common.truth.Truth.assertThat
import io.github.aedev.flow.data.video.downloader.request.DownloadSubtitle
import io.github.aedev.flow.player.state.SubtitleOption
import io.github.aedev.flow.player.state.SubtitleOrigin
import org.junit.Test

class DownloadSubtitleChoiceTest {
    private val english = SubtitleOption(url = "https://yt/en", language = "en", label = "English", isAutoGenerated = false)
    private val englishAuto = SubtitleOption(url = "https://yt/en-asr", language = "en", label = "English", isAutoGenerated = true)
    private val spanishTranslated =
        SubtitleOption(url = "https://yt/en&tlang=es", language = "es", label = "Spanish", isAutoGenerated = true, isTranslated = true)
    private val file =
        SubtitleOption(url = "content://media/1", language = "", label = "Movie.srt", isAutoGenerated = false, origin = SubtitleOrigin.FILE)
    private val embedded =
        SubtitleOption(url = "embedded:3", language = "en", label = "English", isAutoGenerated = false, origin = SubtitleOrigin.EMBEDDED)

    @Test
    fun `only the video's own online tracks can be saved with a download`() {
        assertThat(
            downloadableSubtitles(listOf(english, file, embedded, spanishTranslated)),
        ).containsExactly(english, spanishTranslated).inOrder()
    }

    @Test
    fun `the dialog opens on the last language chosen when the video has it`() {
        val options = listOf(englishAuto, english, spanishTranslated)

        assertThat(defaultDownloadSubtitle(options, "en")).isEqualTo(english)
        assertThat(defaultDownloadSubtitle(options, "es")).isEqualTo(spanishTranslated)
        assertThat(defaultDownloadSubtitle(options, "ja")).isNull()
        assertThat(defaultDownloadSubtitle(options, "")).isNull()
        assertThat(defaultDownloadSubtitle(options, null)).isNull()
    }

    @Test
    fun `a chosen track becomes the request's subtitle`() {
        assertThat(spanishTranslated.toDownloadSubtitle()).isEqualTo(DownloadSubtitle("es", autoGenerated = true, translated = true))
    }
}
